### ISSUE TITLE
The release of the pretrained model.

### ISSUE THREAD

**Issue by nuistji** [sungnyun/understanding-cdfsl#2]
Excellent work and your work inspires me a lot. Can you relase you checkpoint documents of your pretrained model (eg. resnet10 on miniImagent, resnet18 on imagenet)? For the pretraining phase may take me lots of time (especially the training on Imagent). Thanks a lot.

**Comment by sungnyun** [comment]
Hello! Thank you for your interest in our work.

I updated the README doc, and uploaded some of our pretrained model checkpoints [[link](https://github.com/sungnyun/understanding-cdfsl#model-checkpoints)].
Please also note that we used the torchvision model for ImageNet-pretrained ResNet18.
You can turn on this option by using `--imagenet_pretrained` (see line 77 in `./pretrain.py`).

Thanks.

**Comment by nuistji** [comment]
Thank you for your help!
