### ISSUE TITLE
About EMD

### ISSUE THREAD

**Issue by SmartNight-cc** [sungnyun/understanding-cdfsl#4]
Hello! I am also in the research direction of CDFSL. I would like to know if you mentioned in your paper that EMD is used to measure the distance between domains. Is it reflected in the code? I want to refer to the code

**Comment by sungnyun** [comment]
Hi @SmartNight-cc, sorry for the late reply!

Yes, please have a look at our paper, Sec. 3.2. 
You will find our explanation on measuring the EMD. (+ Appx. D describes more details.)

Although we haven't included the code for EMD calculation, you can easily find the necessary Python tool in this link: [https://pypi.org/project/pyemd/0.0.10/](https://pypi.org/project/pyemd/0.0.10/).

Hope this helps you :)

**Comment by sungnyun** [comment]
You can also refer to this [repo](https://github.com/richardaecn/cvpr18-inaturalist-transfer/blob/master/DomainSimilarityDemo.ipynb).
There's an easy-to-follow jupyter notebook.
