### ISSUE TITLE
Request for Additional Dataset Links due to Broken URL

### ISSUE THREAD

**Issue by tinkez** [sungnyun/understanding-cdfsl#8]
The dataset links of 'Cars' provided seem to have encountered a 404 error. Could you please provide alternative links or additional sources for accessing the datasets mentioned? Thank you for your attention to this matter.

**Comment by sungnyun** [comment]
Hi @ypaTinke,

yes, it looks like the link of Cars dataset has been broken by the original source provider.
Thankfully, I have another repo that deals with this dataset.

Check this issue thread. -> https://github.com/sungnyun/openssl-simcore/issues/5#issuecomment-1657344408

**Comment by tinkez** [comment]
Thank you for your response and assistance.
